# Generated by Django 5.2.1 on 2025-05-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telegram_code',
            field=models.CharField(default='d160a241be024607', max_length=16, unique=True),
        ),
    ]
